### ISSUE TITLE
node main.sj <seed> fails with message

### ISSUE THREAD

**Issue by siulynot** [rajivshah3/IOTA-Balance-Finder#3]
```
/home/administrator/balance-finder/main.js:35
    for (let i = 0; i < charsToAdd; i++){
         ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

**Comment by rajivshah3** [comment]
Just fixed 👍  thanks for the report!
